import fs from "node:fs";
import path from "node:path";
import * as p from "@clack/prompts";
import { buildProblemId, type ProblemIdInput } from "./generate-problem/build-problem-id.ts";
import { buildReadmeContent, type ProblemFields } from "./generate-problem/build-readme.ts";
import { buildSolutionStub } from "./generate-problem/build-solution-stub.ts";
import { reindex } from "./reindex.ts";
import {
  LANGUAGE_COLUMN_LABELS,
  LANGUAGES,
  PLATFORM_LABELS,
  PLATFORM_ORDER,
  type ProblemFrontmatter,
} from "./reindex/types.ts";

// CLI glue: interactively prompts for a new problem's details, previews the
// exact files that will be created, and writes them on confirmation.
// Intentionally not unit tested (see spec's Testing Decisions) — the
// id/README/stub content is generated by the tested pure functions in
// ./generate-problem/*; this file only drives the prompts and disk I/O.

function sanitize(input: string): string {
  return input.trim().toLowerCase().replace(/\s+/g, "-");
}

function splitList(input: string, transform: (item: string) => string = (item) => item.trim()): string[] {
  return input
    .split(",")
    .map(transform)
    .filter((item) => item.length > 0);
}

async function textPrompt(message: string): Promise<string> {
  const value = await p.text({ message });
  if (p.isCancel(value)) {
    p.cancel("Cancelled.");
    process.exit(0);
  }
  return value;
}

async function promptIdentity(
  platform: ProblemFrontmatter["platform"],
): Promise<ProblemIdInput> {
  switch (platform) {
    case "leetcode": {
      const number = await textPrompt("Problem number");
      const slug = sanitize(await textPrompt("Slug"));
      return { platform, number: number.trim(), slug };
    }
    case "codeforces": {
      const contest = await textPrompt("Contest number");
      const letter = await textPrompt("Problem letter");
      const slug = sanitize(await textPrompt("Slug"));
      return { platform, contest: contest.trim(), letter: letter.trim(), slug };
    }
    case "hackerrank": {
      const domain = sanitize(await textPrompt("Domain"));
      const slug = sanitize(await textPrompt("Slug"));
      return { platform, domain, slug };
    }
  }
}

async function main(): Promise<void> {
  p.intro("Scaffold a new problem");

  const platform = await p.select({
    message: "Platform",
    options: PLATFORM_ORDER.map((value) => ({
      value,
      label: PLATFORM_LABELS[value],
    })),
  });
  if (p.isCancel(platform)) {
    p.cancel("Cancelled.");
    process.exit(0);
  }

  const identity = await promptIdentity(platform);
  const { id, folderPath } = buildProblemId(identity);

  const difficulty = await textPrompt("Difficulty");
  const tags = splitList(await textPrompt("Tags (comma-separated)"));
  const url = await textPrompt("Problem URL");

  const language = await p.select({
    message: "Language",
    options: LANGUAGES.map((value) => ({
      value,
      label: LANGUAGE_COLUMN_LABELS[value],
    })),
  });
  if (p.isCancel(language)) {
    p.cancel("Cancelled.");
    process.exit(0);
  }

  const approaches = splitList(
    await textPrompt("Approach name(s), comma-separated"),
    sanitize,
  );
  if (approaches.length === 0) {
    p.cancel("At least one approach is required.");
    process.exit(1);
  }

  const root = process.cwd();
  const problemDir = path.join(root, folderPath);
  const languageDir = path.join(problemDir, language);

  const existing = fs.existsSync(languageDir)
    ? fs.readdirSync(languageDir).map((f) => f.replace(/\.[^.]+$/, ""))
    : [];
  const collisions = approaches.filter((approach) =>
    existing.includes(approach),
  );
  if (collisions.length > 0) {
    p.cancel(
      `Already exists: ${collisions.map((a) => `${language}/${a}`).join(", ")}`,
    );
    process.exit(1);
  }

  const fields: ProblemFields = { platform, id, slug: identity.slug, difficulty, tags, url };
  const readmeContent = buildReadmeContent(fields, language, approaches);
  const readmePath = path.join(problemDir, "README.md");

  const stubFiles = approaches.map((approach) => ({
    path: path.join(languageDir, `${approach}.${language}`),
    content: buildSolutionStub(language, approach),
  }));

  const filesToShow = [
    { path: path.relative(root, readmePath), content: readmeContent },
    ...stubFiles.map((f) => ({
      path: path.relative(root, f.path),
      content: f.content,
    })),
  ];

  p.note(
    filesToShow.map((f) => f.path).join("\n"),
    `Will create ${filesToShow.length} file(s) under ${folderPath}/`,
  );
  for (const file of filesToShow) {
    console.log(`\n--- ${file.path} ---\n${file.content}`);
  }

  const confirmed = await p.confirm({ message: "Write these files?" });
  if (p.isCancel(confirmed) || !confirmed) {
    p.cancel("Aborted, nothing written.");
    process.exit(0);
  }

  fs.mkdirSync(languageDir, { recursive: true });
  fs.writeFileSync(readmePath, readmeContent);
  for (const file of stubFiles) {
    fs.writeFileSync(file.path, file.content);
  }

  reindex();

  p.outro(`Created ${folderPath}`);
}

main();
